# Generated by Django 5.0.1 on 2024-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='alert_threshold',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
