# Generated by Django 5.0.1 on 2024-02-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.BigIntegerField()),
                ('title', models.TextField()),
                ('availability', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marketplace',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marketplace')),
            ],
        ),
    ]
